server:
  port: 80
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #服务端收到最后一次心跳后等待时间上限
    lease-expiration-duration-in-seconds: 2
    #服务端发送心跳的间隔
    lease-renewal-interval-in-seconds: 1